### ISSUE TITLE
[BUG] <Not able to npm install and npm start my react project>

### ISSUE THREAD

**Issue by sanjeevarasa-satkunarasa** [npm/installed-package-contents#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not able to run this react app:  [https://github.com/sanjeevarasa-satkunarasa/React-Router-Adopt-Pets](url)

### Steps To Reproduce

1. In this environment Node
2. With this config...
3. Run 'npm install & npm start'

npm install:
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm error code ENOTDIR
npm error syscall mkdir
npm error path G:\My Drive\Personal\Programming\Projects\Codeacademy\react_router_v6_project_starting_code\node_modules\@babel\highlight\node_modules
npm error errno -4052
npm error ENOTDIR: not a directory, mkdir 'G:\My Drive\Personal\Programming\Projects\Codeacademy\react_router_v6_project_starting_code\node_modules\@babel\highlight\node_modules'

npm error A complete log of this run can be found in: C:\Users\ssanj\AppData\Local\npm-cache\_logs\2024-07-26T06_53_29_603Z-debug-0.log

npm start:
$ npm start

> cute-pets-website@0.1.0 start
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

### Environment

- npm: 10.7.0
- Node: 20.15.1
- OS: Windows 
- platform: ThinkPad

**Comment by wraithgar** [comment]
This is a repo for reporting bugs in the `installed-package-contents` package, not general npm cli support.
